### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Prarik** [muukii/NextGrowingTextView#1]
Hello Sir,

Thank you for making this nice control. But can you please tell me how can I get get delegates to be called inside my view control instead of View.swift? 

Thanks

**Comment by JohnEstropia** [comment]
@Prarik 
I'm not sure what you mean with View.swift, but to use the delegates you'll have to assign the closure to the `delegates` property of the textView:
```swift
class MyViewController: UIViewController {

    var textView: NextGrowingTextView?

    override func viewDidLoad() {

        super.viewDidLoad()

        //  self.textView = // ... create self.textView instance

        self.textView?.delegates.textViewDidEndEditing = { (textView) -> Void in
            // Do something
        }
    }
```

**Comment by Prarik** [comment]
Ok got it. Thanks @JohnEstropia
