### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by marcmatta** [muukii/NextGrowingTextView#12]
Hi @muukii ,

Currently, the view is not resizing properly with new line characters: \n if you try to calculate the systemLayoutSizeFiitingSize(UILayoutFittingCompressedSize) after receiving the didChangeHeight delegates event.

The reason is because it is being called before invalidating the intrinsic content size. In your code you have:

```
self.delegates.didChangeHeight(self.frame.height)
self.invalidateIntrinsicContentSize()
```

You should instead switch these two lines as follows and the problem is fixed:

```
self.invalidateIntrinsicContentSize()
self.delegates.didChangeHeight(self.frame.height)
```

Great component you have here. Keep up the good work :+1:

**Comment by muukii** [comment]
@marcmatta 
You're right.
Fixed it!
Thank you.

**Comment by muukii** [comment]
@marcmatta 
I've released new tag.
In 0.6.0, you can use.

**Comment by marcmatta** [comment]
Thanks
