### ISSUE TITLE
How to change keyboard type?

### ISSUE THREAD

**Issue by fatihyildizhan** [muukii/NextGrowingTextView#16]
- Like email address( @ ) or hashtag( # ).

**Comment by muukii** [comment]
@fatihyildizhan 
Sorry.
keyboard type property has not implemented.
I'll add that property on NextGrowingTextView.swift
or Could you submit PR?

**Comment by VLADIMIRR777** [comment]
Please add this property in update.

**Comment by muukii** [comment]
@fatihyildizhan 
@VLADIMIRR777 

You can change keyboard type!

https://github.com/muukii/NextGrowingTextView/pull/25
