### ISSUE TITLE
Dismiss interactively 

### ISSUE THREAD

**Issue by DazChong** [muukii/NextGrowingTextView#17]
Hi, thanks for providing this lightweight controls.

I tried to enable the scrollview dismiss interactively but the view is not supported, then I try to mount it into accessoryView. It also didn't appear with stuck button at bottom right.

```
    override func viewDidLoad() {
        //...
        self.growingTextView.removeFromSuperview()
    }

    override var inputAccessoryView:UIView{
        get{
            return self.growingTextView
        }
    }
```

**Comment by muukii** [comment]
I think It's not in the scope of NextGrowingTextView.
