### ISSUE TITLE
About the Example,why the inputAccessoryView always above the keyboard?

### ISSUE THREAD

**Issue by cielpy** [muukii/NextGrowingTextView#2]
I'm very confused about this,usually I add a observer at viewControllers to listent the frame changes of the input view,I can't find any code about this feature,and in the example project, the input view always above the keyboard, even user change the type of keyboard the input view always follow the key board...please tell me why...thanks a lot

**Comment by muukii** [comment]
@cielpy 
If you want to display the UIView on top of the keyboard, better to use the inputAccessoryView will be simple.
It may be easy to understand and look at the following URL.
http://derpturkey.com/uitextfield-docked-like-ios-messenger/

Thank you.

**Comment by cielpy** [comment]
Thanks a lot.
