### ISSUE TITLE
Access internal textView dynamically

### ISSUE THREAD

**Issue by hiromi2424** [muukii/NextGrowingTextView#21]
We now always have to access internal textView via wrapper.
This means the power of control was missing for non-supporting properties/methods.
We have an option that publishes internal textView to get the power back by just make public visibility of textView:

`public let textView: NextGrowingInternalTextView`

I think wrapper should not prevent accessing the content.
What do you think?

**Comment by muukii** [comment]
Thank you.
> This means the power of control was missing for non-supporting properties/methods.

Yes. I think so too.

The reason why is in this kind of design, it was to prevent access to the delegate.
Because, NextGrowingTextView.swift must have delegate of UITextView.
(Inspired from HPGrowingText)
But, method that does not use the Delegate you might be solved if found.
