### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ryan-blunden** [muukii/NextGrowingTextView#3]
Please! Thanks!

**Comment by muukii** [comment]
@ryan-blunden
I'll do this soon!
Thank you.

**Comment by ryan-blunden** [comment]
If I can help in any way, let me know. I'm not well versed in Xcode build
knowledge but will do whatever I can to assist.
On Friday, 29 January 2016, Hiroshi Kimura <notifications@github.com> wrote:

> @ryan-blunden <https://github.com/ryan-blunden>
> I'll do this soon!
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muukii/NextGrowingTextView/issues/3#issuecomment-176670403>
> .
>


-- 
Cheers,
Ryan

http://www.linkedin.com/in/ryanblunden
http://ryanblunden.com

**Comment by muukii** [comment]
@ryan-blunden 
Sorry.
You can install from carthage
