### ISSUE TITLE
Delegate has strong reference of ViewController

### ISSUE THREAD

**Issue by alice05** [muukii/NextGrowingTextView#30]
Calling methods using delegate keeps the strong reference. Hence viewcontroller never deallocated.

**Comment by dangnguyenhuu** [comment]
my be you need to use  Weak references
`        self.inputField.delegates.textViewDidChange = { [weak self] (growingTextView: NextGrowingTextView) in
            guard let selfView = self else { return}
            let tex = growingTextView.text
            selfView.sendButton.isEnabled = !(tex!.isEmptyField)
            selfView.isTyping = !(tex!.isEmptyField)
        }
`

**Comment by xiaosongshu** [comment]
@dangnguyenhuu thanks, fixed for me! sample code in readme should include [weak self] example, as I was struggling figuring out what was causing the retain cycle
