### ISSUE TITLE
Is this still iOS 7 compatible?

### ISSUE THREAD

**Issue by pjebs** [muukii/NextGrowingTextView#35]
I noticed that you have upgraded to Swift 3 now.
If I'm still using Swift 2, where can I get the latest codebase which is iOS 7 compatible? Is there a final commit id I can use?

**Comment by muukii** [comment]
@pjebs 
Yes, You can use this tag (0.7.3)
https://github.com/muukii/NextGrowingTextView/releases/tag/0.7.3
