### ISSUE TITLE
Version 0.8.4 seems to be wrongly released on CocoaPods

### ISSUE THREAD

**Issue by gskbyte** [muukii/NextGrowingTextView#46]
Hi,

CocoaPods lists `NextGrowingTextView` in the version 0.8.4, but that version can't be added to a Podfile. Actually, the page for the pod is broken: https://cocoapods.org/pods/NextGrowingTextView/

The version number in the `podspec` for 0.8.4 is wrong, that might be the reason: https://github.com/muukii/NextGrowingTextView/blob/0.8.4/NextGrowingTextView.podspec

Thanks!

**Comment by muukii** [comment]
@gskbyte 
Hi,

Thank you for your report!
I've released 0.8.5 🤠

**Comment by gskbyte** [comment]
Thanks!
