### ISSUE TITLE
Access To Inner Text View

### ISSUE THREAD

**Issue by danielchangsoojones** [muukii/NextGrowingTextView#47]
It would be great if you access the inner text view to set properties on it. I would like to be able to turn off the scroll indicator from showing on the inner text view.

**Comment by muukii** [comment]
@danielchangsoojones 
Thank you.
This feature is working now on https://github.com/muukii/NextGrowingTextView/pull/49

**Comment by Urkman** [comment]
Any News on this? The pull request is not merged...
And could you please make a new release after this?

I simply want to disable the TextView...
