### ISSUE TITLE
How to use textViewDidChange with "Revise APIs version" ?

### ISSUE THREAD

**Issue by fatihyildizhan** [muukii/NextGrowingTextView#50]
How can I upgrade this to newer one?

```
let growingTextView: NextGrowingTextView

growingTextView.delegates.textViewDidChange = { (growingTextView: NextGrowingTextView) in
  // Do something
}
```

**Comment by sahuamit13** [comment]
I need textViewDidChange delegate method, how to use in updated version?

let growingTextView: NextGrowingTextView

growingTextView.delegates.textViewDidChange = { (growingTextView: NextGrowingTextView) in
  // Do something
}

**Comment by muukii** [comment]
@fatihyildizhan @sahuamit13 

`delegates.textViewDidChange` was deprecated.
You can now use UITextViewDelegate from `NextGrowingTextView.textView.delegate`

**Comment by sahuamit13** [comment]
Hi muukii,

Thanks for your reply

 UITextViewDelegate from NextGrowingTextView.textView.delegate

can you explain through it with example

Thanks

**Comment by muukii** [comment]
@sahuamit13 

okay,
It may works.

```swift

class ViewController: UIViewController {
  
  let nextTextView: NextGrowingTextView = ...

  override func viewDidLoad() {
    super.viewDidLoad()
    
    nextTextView.textView.delegate = self    
  }
}

extension ViewController: UITextViewDelegate {
  func textViewDidChange(_ textView: UITextView) {
    // here 🤠
  }
}
```

**Comment by sahuamit13** [comment]
Hi muukii,

Thanks it's working now..

**Comment by muukii** [comment]
Hi

Nice🎉
