### ISSUE TITLE
Not working on iOS 11?

### ISSUE THREAD

**Issue by genaks** [muukii/NextGrowingTextView#59]
I don't think this is properly working on iOS 11. The text field stays at the bottom even when the keyboard comes up.

**Comment by muukii** [comment]
@genaks 
NextGrowingTextView does not have an implementation that is attracted to the keyboard.
You need to implement it that likes demo.

**Comment by bnareshgoud413** [comment]
not working in ios 1

**Comment by muukii** [comment]
How is not working on iOS 11?

**Comment by muukii** [comment]
Sorry, I close this.
