### ISSUE TITLE
UIMenuController will be shown on wrong point, when select all.

### ISSUE THREAD

**Issue by muukii** [muukii/NextGrowingTextView#8]
![simulator screen shot mar 28 2016 10 22 41 pm](https://cloud.githubusercontent.com/assets/1888355/14078842/12265d4a-f534-11e5-9456-897ecaddd6c5.png)

**Comment by kedarchiselcut** [comment]
Any update on this?

**Comment by muukii** [comment]
@kedarchiselcut 
No, I have no idea. 😱

**Comment by muukii** [comment]
It happens when text lines is greater than maximum number of lines.

**Comment by muukii** [comment]
https://github.com/muukii/NextGrowingTextView/pull/91

**Comment by muukii** [comment]
https://github.com/muukii/NextGrowingTextView/pull/91
